### ISSUE TITLE
Getting confidence scores

### ISSUE THREAD

**Issue by yurifariasg** [srvk/eesen-transcriber#3]
Hi,

I've been trying to get the confidence scores for the output text extracted. I reached out to Tanel Alumae, who suggested that I should modify the Makefile to use get_ctm_conf.sh instead of get_ctm.sh while building the output files. I tried to perform this change on this adapted version of the transcriber but it seems like this version does not use the get_ctm script at all. The output files were not changed.

Does anyone has any suggestion on how can I get the confidence scores? Or how can I make the Makefile use the get_ctm/get_ctm_conf scripts ?

Thanks

**Comment by riebling** [comment]
I see the primary difference between get_ctm.sh in eesen-transcriber system and
get_ctm_conf.sh (only to be found in Kaldi's egs/aspire experiment, it seems),
exists in these lines:

get_ctm_conf.sh (aspire/s5 example in Kaldi)

```
 $cmd LMWT=$min_lmwt:$max_lmwt $dir/scoring/log/get_ctm.LMWT.log \
   mkdir -p $dir/score_LMWT/ '&&' \
   lattice-prune --inv-acoustic-scale=LMWT --beam=5 "ark:gunzip -c $dir/lat.*.gz|" ark:- \| \
   lattice-align-words-lexicon $lang/phones/align_lexicon.int $model ark:- ark:- \| \
   lattice-to-ctm-conf --decode-mbr=true --inv-acoustic-scale=LMWT ark:- - \| \
   utils/int2sym.pl -f 5 $lang/words.txt \| \
   $filter_cmd '>' $dir/score_LMWT/$name.ctm || exit 1;
```

get_ctm.sh (srvk/eesen-transcriber):

# We are not using lattice-align-words, which may result in minor degradation

if [ $stage -le 0 ]; then
   $cmd ACWT=$min_acwt:$max_acwt $dir/scoring/log/get_ctm.ACWT.log \
     mkdir -p $dir/score_ACWT/ '&&' \
     lattice-1best --acoustic-scale=ACWT --ascale-factor=$acwt_factor "ark:gunzip -c $dir/lat.*.gz|" ark:- | \
     nbest-to-ctm ark:- - | \
     utils/int2sym.pl -f 5 $symtab \
     '>' $dir/score_ACWT/$name.ctm || exit 1;
fi

So it is possible to edit get_ctm.sh in eesen-transcriber to perform
the functions that are done in get_ctm_conf.sh. But the REAL problem is: eesen
transcriber is built from a minimal system that only contains PARTS of Kaldi, it
specifically does NOT have these needed programs:

lattice-prune
lattice-align-words
lattice-to-ctm-conf

The path to success would be to add these Kaldi programs to the EESEN
source https://github.com/srvk/eesen/tree/master/src such that they are
available in the VM.

A path towards doing THIS (even more hacking) would be to use an older
version of srvk/eesen-transcriber that is based on the mario-kaldi.box
base box (see Vagrantfile history). - in this earlier VM, all of Kaldi is present,
including the above programs and even get_ctm_conf.sh, such as it is.

On 03/07/2016 09:23 AM, Yuri Farias Gomes wrote:

> Hi,
> 
> I've been trying to get the confidence scores for the output text extracted. I reached out to Tanel Alumae, who suggested that I should modify the Makefile to use get_ctm_conf.sh instead of get_ctm.sh while building the output files. I tried to perform this change on this adapted version of the transcriber but it seems like this version does not use the get_ctm script at all. The output files were not changed.
> 
> Does anyone has any suggestion on how can I get the confidence scores? Or how can I make the Makefile use the get_ctm/get_ctm_conf scripts ?
> 
> Thanks
> 
> —
> Reply to this email directly or view it on GitHub https://github.com/srvk/eesen-transcriber/issues/3.

## 

Eric Riebling      Interactive Systems Lab
er1k@cs.cmu.edu    407 South Craig St.

**Comment by yurifariasg** [comment]
Hi @riebling,

I followed the steps you suggested, but it seems like there's something else missing:

`/home/vagrant/kaldi-trunk/egs/aspire/s5/local/multi_condition/get_ctm_conf.sh: expecting file build/trans/sample3/eesen/decode/../final.mdl to exist`

It looks like the get_ctm.sh is a modified version of the script that does not use lattice-align-words, as shown on script's documentation:

`# get_ctm.sh for nnet decode WITHOUT a final.mdl - skips lattice-align-words`

Is there a way to generate this final.mdl file ?

Thanks for the help!

**Comment by riebling** [comment]
We're working on adding confidences! Thanks for trying, also.
Rather than pull in all of Kaldi, we're trying to add the missing programs
to EESEN, and then work out the scripting details. Will let you know here
when things seem ready.

Best,

-er

On 03/08/2016 09:20 AM, Yuri Farias Gomes wrote:

> Hi @riebling https://github.com/riebling,
> 
> I followed the steps you suggested, but it seems like there's something else missing:
> 
> |/home/vagrant/kaldi-trunk/egs/aspire/s5/local/multi_condition/get_ctm_conf.sh: expecting file build/trans/sample3/eesen/decode/../final.mdl to exist|
> 
> It looks like the get_ctm.sh is a modified version of the script that does not use lattice-align-words, as shown on script's documentation:
> 
> |# get_ctm.sh for nnet decode WITHOUT a final.mdl - skips lattice-align-words|
> 
> Is there a way to generate this final.mdl file ?
> 
> Thanks for the help!
> 
> —
> Reply to this email directly or view it on GitHub https://github.com/srvk/eesen-transcriber/issues/3#issuecomment-193801441.

## 

Eric Riebling      Interactive Systems Lab
er1k@cs.cmu.edu    407 South Craig St.

**Comment by riebling** [comment]
We've made a slight modification to `lattice-to-ctm-conf.cc` to make it work more like `lattice-1best`. If you make `get_ctm.sh` or `get_ctm_conf.sh` look more like this:

```
     $cmd ACWT=$min_acwt:$max_acwt $dir/scoring/log/get_ctm.ACWT.log \
      mkdir -p $dir/score_ACWT/ '&&' \
      lattice-to-ctm-conf --decode-mbr=true --acoustic-scale=ACWT --ascale-factor=$acwt_factor "ark:gunzip -c $dir/lat.*.gz|" - \| \
      utils/int2sym.pl -f 5 $symtab \
      '>' $dir/score_ACWT/$name.ctm || exit 1;
```

This has the benefit of allowing acoustic-scale to be an integer so that `$cmd=run.pl`
can vary it between `min_acwt` and `max_acwt`.  

I've pushed `lattice-to-ctm-conf.cc` to [My eesen fork](https://github.com/riebling/eesen) for consideration
