### ISSUE TITLE
Allow running on AWS

### ISSUE THREAD

**Issue by fmetze** [srvk/eesen-transcriber#6]
Is it possible to run this on AWS and Virtualbox

**Comment by riebling** [comment]
There are some challenges to making this run 'in the same way' on AWS and VirtualBox due to host filesystem shared folders. Investigation stopped at the point where NFS could not be configured automatically, but even when it was set up and working, the filesystem appeared to be read only from one end. Several issues exist using NFS as the shared folder mechanism with Vagrant, but I think our experience has shown sshfs to be a preferable solution, and should be used for eesen-transcriber on AWS.

**Comment by fmetze** [comment]
Right, there are two things:
- building it requires some cases where you have to distinguish between Amazon Linux and Ubuntu
- running it requires a shared file-system and SSHFS would be the preferred way to set this up

Do we want to implement this?

> On Mar 24, 2016, at 1:15 AM, riebling notifications@github.com wrote:
> 
> There are some challenges to making this run 'in the same way' on AWS and VirtualBox due to host filesystem shared folders. Investigation stopped at the point where NFS could not be configured automatically, but even when it was set up and working, the filesystem appeared to be read only from one end. Several issues exist using NFS as the shared folder mechanism with Vagrant, but I think our experience has shown sshfs to be a preferable solution, and should be used for eesen-transcriber on AWS.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub https://github.com/srvk/eesen-transcriber/issues/6#issuecomment-200447636

Florian Metze http://www.cs.cmu.edu/directory/florian-metze
Associate Research Professor
Carnegie Mellon University
